import "aos/dist/aos.css";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import ContourBackground from "./backgraund";
import "./globals.css";
import Navbar from "./Navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "DEV-BRO | Home",
  description: "Generated by create next app",
  icons: {
    icon: "/fovicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col items-center justify-center contenr bg-black ">
        <Toaster position="top-center" />
        <ContourBackground />
        <Navbar />
        <main className="min-h-full flex flex-col lg:mt-[120px] mt-[120px] w-full max-w-[1300px]">
          {children}
        </main>
      </body>
    </html>
  );
}
